Egyptian Food World website
Maha-Magdy/egyptian-food-world pull request #27
Opened 2021-09-16 22:38 UTC by Maha-Magdy

2021-09-16 22:46 UTC, vichuge requested changes
# Project invalidated 🚫 

Hi there, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![cat_massage](https://user-images.githubusercontent.com/20563252/121368971-16d2dc00-c901-11eb-9123-7f578bf64118.gif)

## Why does this happen ❓ ❓ ❓ 

You have submitted a project, that has some linters errors, please fix them before to ask another code review. 
![image](https://user-images.githubusercontent.com/20563252/133695102-2657d978-eca0-40c8-a363-c05410847713.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-09-17 00:32 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your PR messages are descriptive ✔️

## Aspects to improve ♻️

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-17 00:32 UTC, vichuge commented on src/homepage.js
> +export function updateMealsNumber(mealsList) {
- [ ] It looks like here we could use ES6 best practices (in this case arrow function). 🐱

2021-09-17 00:32 UTC, vichuge commented on src/homepage.js
> +function createMealsObject(mealsList, likesList) {
- [ ] It looks like here we could use ES6 best practices (in this case arrow function). 🐱

2021-09-17 00:32 UTC, vichuge commented on src/homepage.js
> +async function egyptianMeals() {
- [ ] It looks like here we could use ES6 best practices (in this case arrow function). 🐱

2021-09-17 00:32 UTC, vichuge commented on src/meal.js
> +async function listComments(itemId) {
- [ ] It looks like here we could use ES6 best practices (in this case arrow function). 🐱

2021-09-17 00:32 UTC, vichuge commented on src/meal.js
> +async function addComment(itemId) {
- [ ] It looks like here we could use ES6 best practices (in this case arrow function). 🐱

2021-09-17 00:32 UTC, vichuge commented on src/meal.js
> +/* eslint-disable array-callback-return */
- [ ] It looks like you're using some disablers here, it's ok if we're struggling with some issues and then we use it to continue 1 or 2 times, please, try to do the code without disabling a lot of functions here. 🌵

2021-09-17 00:32 UTC, vichuge commented on README.md
> +
- [ ] I'm afraid I couldn't find the video presentation on the pull request description or the readme file, please add it. 🐶

2021-09-17 18:58 UTC, descholar-ceo approved these changes
Hi @Maha-Magdy and @MaiRizk , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-17 22:55 UTC, merged